
"""schema

Revision ID: 242c17a0a509
Revises: 90a6837b7a26
Create Date: 2025-10-21 00:10:59.601375
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242c17a0a509'
down_revision: Union[str, None] = '90a6837b7a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateways_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_gateway', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateways_metodos_pago_id'), 'gateways_metodos_pago', ['id'], unique=False)
    op.create_table('marcas_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_marca', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_metodos_pago_id'), 'marcas_metodos_pago', ['id'], unique=False)
    op.create_table('tipos_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_metodo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_metodos_pago_id'), 'tipos_metodos_pago', ['id'], unique=False)
    op.drop_index(op.f('idx_usuario_metodo_pago__id_metodo_pago'), table_name='usuario_metodo_pago')
    op.drop_table('usuario_metodo_pago')
    op.drop_index(op.f('idx_info_metodo_pago__id_usuario_metodo_pago'), table_name='informacion_metodo_pago')
    op.drop_table('informacion_metodo_pago')
    op.alter_column('estado_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('estado_pago', 'nombre_estado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_estado_pago_id'), 'estado_pago', ['id'], unique=False)
    op.add_column('metodos_pago', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('metodos_pago', sa.Column('tipo_pago_id', sa.Integer(), nullable=False))
    op.add_column('metodos_pago', sa.Column('marca_pago_id', sa.Integer(), nullable=True))
    op.add_column('metodos_pago', sa.Column('gateway_pago_id', sa.Integer(), nullable=True))
    op.add_column('metodos_pago', sa.Column('es_default', sa.Boolean(), nullable=False))
    op.add_column('metodos_pago', sa.Column('identificador_wallet', sa.String(), nullable=True))
    op.alter_column('metodos_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_foreign_key(None, 'metodos_pago', 'marcas_metodos_pago', ['marca_pago_id'], ['id'])
    op.create_foreign_key(None, 'metodos_pago', 'tipos_metodos_pago', ['tipo_pago_id'], ['id'])
    op.create_foreign_key(None, 'metodos_pago', 'gateways_metodos_pago', ['gateway_pago_id'], ['id'])
    op.drop_column('metodos_pago', 'nombre_metodo')
    op.alter_column('orden_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orden_pago', 'nombre_estado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_orden_pago__id_estado_pago'), table_name='orden_pago')
    op.drop_index(op.f('idx_orden_pago__id_pago'), table_name='orden_pago')
    op.create_index(op.f('ix_orden_pago_id'), 'orden_pago', ['id'], unique=False)
    op.add_column('pagos', sa.Column('metodo_pago_id', sa.Integer(), nullable=False))
    op.alter_column('pagos', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pagos', 'nro_cuenta',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_pagos__estado_actual'), table_name='pagos')
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_foreign_key(None, 'pagos', 'metodos_pago', ['metodo_pago_id'], ['id'])
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos', type_='foreignkey')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.create_index(op.f('idx_pagos__estado_actual'), 'pagos', ['estado_actual'], unique=False)
    op.alter_column('pagos', 'nro_cuenta',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('pagos', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('pagos', 'metodo_pago_id')
    op.drop_index(op.f('ix_orden_pago_id'), table_name='orden_pago')
    op.create_index(op.f('idx_orden_pago__id_pago'), 'orden_pago', ['id_pago'], unique=False)
    op.create_index(op.f('idx_orden_pago__id_estado_pago'), 'orden_pago', ['id_estado_pago'], unique=False)
    op.alter_column('orden_pago', 'nombre_estado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orden_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('metodos_pago', sa.Column('nombre_metodo', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'metodos_pago', type_='foreignkey')
    op.drop_constraint(None, 'metodos_pago', type_='foreignkey')
    op.drop_constraint(None, 'metodos_pago', type_='foreignkey')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.alter_column('metodos_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('metodos_pago', 'identificador_wallet')
    op.drop_column('metodos_pago', 'es_default')
    op.drop_column('metodos_pago', 'gateway_pago_id')
    op.drop_column('metodos_pago', 'marca_pago_id')
    op.drop_column('metodos_pago', 'tipo_pago_id')
    op.drop_column('metodos_pago', 'usuario_id')
    op.drop_index(op.f('ix_estado_pago_id'), table_name='estado_pago')
    op.alter_column('estado_pago', 'nombre_estado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('estado_pago', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('informacion_metodo_pago',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('cod_seguridad', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_vencimiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('nombre_titular', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nro_tarjeta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_metodo_pago', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_metodo_pago'], ['usuario_metodo_pago.id'], name=op.f('fk_info_mp__usuario_mp')),
    sa.PrimaryKeyConstraint('id', name=op.f('informacion_metodo_pago_pkey'))
    )
    op.create_index(op.f('idx_info_metodo_pago__id_usuario_metodo_pago'), 'informacion_metodo_pago', ['id_usuario_metodo_pago'], unique=False)
    op.create_table('usuario_metodo_pago',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_metodo_pago', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_externo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora_alta', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('fecha_hora_baja', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], name=op.f('fk_usuario_metodo__metodo')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_metodo_pago_pkey'))
    )
    op.create_index(op.f('idx_usuario_metodo_pago__id_metodo_pago'), 'usuario_metodo_pago', ['id_metodo_pago'], unique=False)
    op.drop_index(op.f('ix_tipos_metodos_pago_id'), table_name='tipos_metodos_pago')
    op.drop_table('tipos_metodos_pago')
    op.drop_index(op.f('ix_marcas_metodos_pago_id'), table_name='marcas_metodos_pago')
    op.drop_table('marcas_metodos_pago')
    op.drop_index(op.f('ix_gateways_metodos_pago_id'), table_name='gateways_metodos_pago')
    op.drop_table('gateways_metodos_pago')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
