
"""schema

Revision ID: 2a6f4df62bde
Revises: 49e5ea0e2cf7
Create Date: 2025-10-21 01:18:14.664898
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6f4df62bde'
down_revision: Union[str, None] = '49e5ea0e2cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orden_pago_id'), table_name='orden_pago')
    op.drop_table('orden_pago')
    op.add_column('pagos', sa.Column('orden_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'orden_id')
    op.create_table('orden_pago',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_externa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_pago', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_estado_pago', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora_alta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_hora_baja', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nombre_estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_estado_pago'], ['estado_pago.id'], name=op.f('orden_pago_id_estado_pago_fkey')),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id'], name=op.f('orden_pago_id_pago_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orden_pago_pkey'))
    )
    op.create_index(op.f('ix_orden_pago_id'), 'orden_pago', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
