
"""cambuios

Revision ID: 63f8fa53ba5a
Revises: c27d12b07aa0
Create Date: 2025-10-30 23:29:18.739633
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f8fa53ba5a'
down_revision: Union[str, None] = 'c27d12b07aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_banco', sa.String(), nullable=False),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancos_id'), 'bancos', ['id'], unique=False)
    op.create_table('monedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moneda_nombre', sa.String(), nullable=False),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monedas_id'), 'monedas', ['id'], unique=False)
    op.create_table('proveedores_billetera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_gateway', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_billetera_id'), 'proveedores_billetera', ['id'], unique=False)
    op.create_table('metodos_pago_billetera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('moneda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['monedas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores_billetera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_billetera_id'), 'metodos_pago_billetera', ['id'], unique=False)
    op.create_table('metodos_pago_tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_pago_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('numero_tarjeta', sa.String(), nullable=False),
    sa.Column('ultimos_cuatro_digitos', sa.String(), nullable=True),
    sa.Column('fecha_vencimiento', sa.String(), nullable=False),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marca_pago_id'], ['marcas_metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_tarjeta_id'), 'metodos_pago_tarjeta', ['id'], unique=False)
    op.create_table('orden_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_externa_id', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_estado_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado_pago'], ['estado_pago.id'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_pago_id'), 'orden_pago', ['id'], unique=False)
    op.add_column('metodos_pago', sa.Column('moneda_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('metodos_pago_marca_pago_id_fkey'), 'metodos_pago', type_='foreignkey')
    op.create_foreign_key(None, 'metodos_pago', 'monedas', ['moneda_id'], ['id'])
    op.drop_column('metodos_pago', 'ultimos_cuatro_digitos')
    op.drop_column('metodos_pago', 'identificador_wallet')
    op.drop_column('metodos_pago', 'gateway_pago_id')
    op.drop_column('metodos_pago', 'numero_tarjeta')
    op.drop_column('metodos_pago', 'marca_pago_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodos_pago', sa.Column('marca_pago_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metodos_pago', sa.Column('numero_tarjeta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metodos_pago', sa.Column('gateway_pago_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metodos_pago', sa.Column('identificador_wallet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metodos_pago', sa.Column('ultimos_cuatro_digitos', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'metodos_pago', type_='foreignkey')
    op.create_foreign_key(op.f('metodos_pago_marca_pago_id_fkey'), 'metodos_pago', 'marcas_metodos_pago', ['marca_pago_id'], ['id'])
    op.drop_column('metodos_pago', 'moneda_id')
    op.drop_index(op.f('ix_orden_pago_id'), table_name='orden_pago')
    op.drop_table('orden_pago')
    op.drop_index(op.f('ix_metodos_pago_tarjeta_id'), table_name='metodos_pago_tarjeta')
    op.drop_table('metodos_pago_tarjeta')
    op.drop_index(op.f('ix_metodos_pago_billetera_id'), table_name='metodos_pago_billetera')
    op.drop_table('metodos_pago_billetera')
    op.drop_index(op.f('ix_proveedores_billetera_id'), table_name='proveedores_billetera')
    op.drop_table('proveedores_billetera')
    op.drop_index(op.f('ix_monedas_id'), table_name='monedas')
    op.drop_table('monedas')
    op.drop_index(op.f('ix_bancos_id'), table_name='bancos')
    op.drop_table('bancos')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
