
"""cambios

Revision ID: 7a1cb9e424ad
Revises: 63f8fa53ba5a
Create Date: 2025-11-02 00:15:11.328521
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1cb9e424ad'
down_revision: Union[str, None] = '63f8fa53ba5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodos_pago', sa.Column('metodo_pago_detalle_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('metodos_pago_billetera_metodo_pago_id_fkey'), 'metodos_pago_billetera', type_='foreignkey')
    op.drop_column('metodos_pago_billetera', 'metodo_pago_id')
    op.add_column('metodos_pago_tarjeta', sa.Column('nombre_titular', sa.String(), nullable=False))
    op.add_column('metodos_pago_tarjeta', sa.Column('banco_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('metodos_pago_tarjeta_metodo_pago_id_fkey'), 'metodos_pago_tarjeta', type_='foreignkey')
    op.create_foreign_key(None, 'metodos_pago_tarjeta', 'bancos', ['banco_id'], ['id'])
    op.drop_column('metodos_pago_tarjeta', 'metodo_pago_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodos_pago_tarjeta', sa.Column('metodo_pago_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'metodos_pago_tarjeta', type_='foreignkey')
    op.create_foreign_key(op.f('metodos_pago_tarjeta_metodo_pago_id_fkey'), 'metodos_pago_tarjeta', 'metodos_pago', ['metodo_pago_id'], ['id'])
    op.drop_column('metodos_pago_tarjeta', 'banco_id')
    op.drop_column('metodos_pago_tarjeta', 'nombre_titular')
    op.add_column('metodos_pago_billetera', sa.Column('metodo_pago_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('metodos_pago_billetera_metodo_pago_id_fkey'), 'metodos_pago_billetera', 'metodos_pago', ['metodo_pago_id'], ['id'])
    op.drop_column('metodos_pago', 'metodo_pago_detalle_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
