
"""empty message

Revision ID: 80f3cdbef9fe
Revises: 7a1cb9e424ad
Create Date: 2025-11-08 17:41:22.268690
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f3cdbef9fe'
down_revision: Union[str, None] = '7a1cb9e424ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'monto_pagado')
    op.drop_column('pagos', 'nro_cuenta')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('nro_cuenta', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pagos', sa.Column('monto_pagado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
    # ### end Alembic commands ###
