
"""schema

Revision ID: af6ec5fe3675
Revises: c35b67149888
Create Date: 2025-10-21 00:34:24.056228
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6ec5fe3675'
down_revision: Union[str, None] = 'c35b67149888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodos_pago', sa.Column('ultimos_cuatro_digitos', sa.String(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metodos_pago', 'ultimos_cuatro_digitos')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
