
"""schema

Revision ID: c35b67149888
Revises: 242c17a0a509
Create Date: 2025-10-21 00:14:50.322279
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35b67149888'
down_revision: Union[str, None] = '242c17a0a509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_pago_id'), 'estado_pago', ['id'], unique=False)
    op.create_table('gateways_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_gateway', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateways_metodos_pago_id'), 'gateways_metodos_pago', ['id'], unique=False)
    op.create_table('marcas_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_marca', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_metodos_pago_id'), 'marcas_metodos_pago', ['id'], unique=False)
    op.create_table('tipos_metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_metodo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_metodos_pago_id'), 'tipos_metodos_pago', ['id'], unique=False)
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pago_id', sa.Integer(), nullable=False),
    sa.Column('marca_pago_id', sa.Integer(), nullable=True),
    sa.Column('gateway_pago_id', sa.Integer(), nullable=True),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('identificador_wallet', sa.String(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_pago_id'], ['gateways_metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['marca_pago_id'], ['marcas_metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['tipo_pago_id'], ['tipos_metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_creacion', sa.DateTime(), nullable=True),
    sa.Column('nro_cuenta', sa.String(), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('estado_actual', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_actual'], ['estado_pago.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('orden_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_externa_id', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_estado_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_hora_baja', sa.DateTime(), nullable=True),
    sa.Column('nombre_estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado_pago'], ['estado_pago.id'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_pago_id'), 'orden_pago', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orden_pago_id'), table_name='orden_pago')
    op.drop_table('orden_pago')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    op.drop_index(op.f('ix_tipos_metodos_pago_id'), table_name='tipos_metodos_pago')
    op.drop_table('tipos_metodos_pago')
    op.drop_index(op.f('ix_marcas_metodos_pago_id'), table_name='marcas_metodos_pago')
    op.drop_table('marcas_metodos_pago')
    op.drop_index(op.f('ix_gateways_metodos_pago_id'), table_name='gateways_metodos_pago')
    op.drop_table('gateways_metodos_pago')
    op.drop_index(op.f('ix_estado_pago_id'), table_name='estado_pago')
    op.drop_table('estado_pago')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
