
"""schema

Revision ID: dcd87e2ab97b
Revises: af6ec5fe3675
Create Date: 2025-10-21 00:39:08.978283
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd87e2ab97b'
down_revision: Union[str, None] = 'af6ec5fe3675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metodos_pago', sa.Column('numero_tarjeta', sa.String(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metodos_pago', 'numero_tarjeta')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
